name: e3dady_app
description: تطبيق اعدادي للصلاة
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  
  # Storage
  shared_preferences: ^2.2.0
  
  # 🔥 الإشعارات
  flutter_local_notifications: ^18.0.0
  workmanager: ^0.6.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

# 🔥 إعداد اللوجو
flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"
